# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: 'latest'
  imageName: 'hungthuanmk/mcbot'

stages:
- stage: Docker
  displayName: Build image
  jobs:
  - job: Docker
    displayName: Build & push
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build & push image
      inputs:
        command: buildAndPush
        dockerfile: '**/Dockerfile'
        containerRegistry: 'dockerhub-hungthuanmk'
        repository: $(imageName)
        tags: |
          $(tag)
          
